# Service
apiVersion: v1
kind: Service
metadata:
    name: kapi-service
spec: 
    selector:
        ms: kapi-base
    ports: 
        - protocol: TCP
          port: 8080
          targetPort: 8080
---
# This file defines the K8S Deployment object for uppics
apiVersion: apps/v1
kind: Deployment
metadata: 
    name: kapi-base-dep
    labels: 
        ms: kapi-base
spec: 
    replicas: 1
    revisionHistoryLimit: 0
    selector:
        matchLabels:
            ms: kapi-base
    template:
        metadata:
            labels: 
                ms: kapi-base
        spec: 
            containers: 
                - name: kapi-base
                  image: nicolasances/kapi-base:1.0.0
                  ports: 
                    - containerPort: 8080